on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
jobs:
    run-tests:
      name: run-tests
      runs-on: ubuntu-latest

      environment: dev
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Python Init
          uses: actions/setup-python@v5
          with:
            python-version: '3.11.1'
               
        - name: Run Requirements
          run: make all-requirements
        
        - name: Run Dev-Setup
          run: make dev-setup
       
        - name: Run Tests
          run: make run-checks
        
    deploy-lambda:
      name: deploy-lambda
      runs-on: ubuntu-latest
      needs: run-tests
      environment: dev
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Python Init
          uses: actions/setup-python@v5
          with:
            python-version: '3.11.1'
        - name: Run Requirements
          run: make all-requirements
        - name: Terraform install
          uses: hashicorp/setup-terraform@v3
        - name: AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        
        - name: Install Dependencies
          run: make custom-dependencies
        - name: Terraform Init
          working-directory: terraform
          run: terraform init
        - name: Terraform plan
          working-directory: terraform
          run: terraform plan
        - name: Terraform apply
          working-directory: terraform
          run: terraform apply --auto-approve

#rogue comment